export const CONTRACT_ADDRESSES = {
  GAME_CONTRACT: import.meta.env.VITE_REACT_APP_GAME_CONTRACT_ADDRESS as string
};

export const CONTRACT_CONFIGS = {
  JUMP_COST: "0.0001",
  POWER_UP_COST: "0.0005"
}; 